### PR TITLE
Add cronsul to list of tools

### PR DESCRIPTION
**Pull request by josegonzalez**

### CODE REVIEW

**Comment by josegonzalez** [comment]
Note: I think @liangshan may have stepped away from OSS, so my fork will probably contain a bunch of updates that can be pulled in whenever desired.

**Comment by liangshan** [comment]
yeah, i'm not following the news about consul recently, i will add a NOTE and a link to your fork in the README.

**Comment by josegonzalez** [comment]
@liangshan you could also transfer the repository to me and I'd be happy to maintain it :)

**Comment by liangshan** [comment]
sure, but you have to rename the forked repo or delete first then restore it from your local repo. i can't transfer the repo when it already exists.

**Comment by josegonzalez** [comment]
Renamed :)

**Comment by liangshan** [comment]
> josegonzalez already has a repository in the liangshan/awesome-consul network

seams like you have to delete it first.

**Comment by josegonzalez** [comment]
Done.

**Pull request closed without merging**
